- name: install epel
  dnf:
    name: epel-release
    state: latest
    update_cache: "expire-cache"

- name: install nvidia-driver-module
  dnf:
    name: "@nvidia-driver:latest-dkms"
    state: {{ nvidia_driver_package_version }}
    update_cache: "expire-cache"

- name: install dependencies
  dnf:
    name: dkms

- name: add repo
  yum_repository:
    name: cuda
    description: NVIDIA CUDA YUM Repo
    baseurl: "{{ nvidia_driver_rhel_cuda_repo_baseurl }}"
    gpgkey: "{{ nvidia_driver_rhel_cuda_repo_gpgkey }}"
  environment: "{{ proxy_env if proxy_env is defined else {}}}"

- name: install driver packages
  dnf:
    name: "{{ nvidia_driver_package_version | ternary('nvidia-driver-latest-dkms-'+nvidia_driver_package_version, 'nvidia-driver-latest-dkms') }}"
    state: "{{ nvidia_driver_package_state }}"
    autoremove: "{{ nvidia_driver_package_state == 'absent' }}"
  register: install_driver
  environment: "{{proxy_env if proxy_env is defined else {}}}"

