---
# We have to do this because the CentOS mirrors don't keep kernel-headers, etc
# for older kernels.
- name: ensure we have kernel-headers installed for the current kernel
  block:
    - name: attempt to install kernel support packages for current version
      dnf:
        name: "{{ item }}-{{ ansible_kernel }}"
        state: latest
      with_items:
        - "kernel-headers-{{ rhel_kernel_version }}"
        - "kernel-tools-{{ rhel_kernel_version }}"
        - "kernel-tools-libs-{{ rhel_kernel_version }}"
        - "kernel-devel-{{ rhel_kernel_version }}"
        - "kernel-debug-devel-{{ rhel_kernel_version }}"
      environment: "{{proxy_env if proxy_env is defined else {}}}"
  rescue:
      #- name: install kernel support packages for curent version
      #dnf:
      #name: ['kernel-headers','kernel-tools','kernel-tools-libs','kernel-devel','kernel-debug-devel']
      #environment: "{{proxy_env if proxy_env is defined else {}}}"

  - name: update the kernel to latest version so we have a supported version
    dnf:
      name:
        - "kernel-{{ rhel_kernel_version }}"
        - "kernel-headers-{{ rhel_kernel_version }}"
        - "kernel-tools-{{ rhel_kernel_version }}"
        - "kernel-tools-libs-{{ rhel_kernel_version }}"
        - "kernel-devel-{{ rhel_kernel_version }}"
        - "kernel-debug-devel-{{ rhel_kernel_version }}"
      state: present
    environment: "{{proxy_env if proxy_env is defined else {}}}"
