---
- name: unload nouveau
  modprobe:
    name: nouveau
    state: absent
  ignore_errors: true

- name: ubuntu install tasks
  include_tasks: install-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: redhat family version 7 install tasks
  include_tasks: install-redhat-7.yml
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "7"

- name: redhat family version 8 install tasks stage 1
  include_tasks: install-redhat-8-stage1.yml
  #when: ansible_os_family == 'RedHat'
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "8"
    - build_stage == 1

- name: redhat family version 8 install tasks stage 2
  include_tasks: install-redhat-8-stage2.yml
  #when: ansible_os_family == 'RedHat'
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "8"
    - build_stage == 2

##
#- name: create persistenced override dir
#  file:
#    path: /etc/systemd/system/nvidia-persistenced.service.d/
#    state: directory
#    recurse: yes
#
#- name: configure persistenced service to turn on persistence mode
#  copy:
#    src: nvidia-persistenced-override.conf
#    dest: /etc/systemd/system/nvidia-persistenced.service.d/override.conf
#  when: nvidia_driver_persistence_mode_on
#
#- name: remove persistenced service override
#  file:
#    path: /etc/systemd/system/nvidia-persistenced.service.d/override.conf
#    state: absent
#  when: not nvidia_driver_persistence_mode_on
#
#
#- name: enable persistenced
#  systemd:
#    name: nvidia-persistenced
#    enabled: yes
#  when: nvidia_driver_package_state != 'absent'
#
#- name: set module parameters
#  template:
#    src: nvidia.conf.j2
#    dest: "{{ nvidia_driver_module_file }}"
#    mode: '0644'
#
#- name: reboot after driver install
#  reboot:
#  when: install_driver.changed and not nvidia_driver_skip_reboot
